#Sam Dressler
#HW 10 Makefile
#compiler
CC = g++
#compiler flags
CC_FLAGS = -g -Wall -lpthread -lrt
HEADERS = program0.h program1.h program2.h program3.h 

all: 
	$(CC)  program0.cpp $(CC_FLAGS) -o program0
	$(CC)  program1.cpp $(CC_FLAGS) -o program1
	$(CC)  program2.cpp $(CC_FLAGS) -o program2
	$(CC)  program3.cpp $(CC_FLAGS) -o program3

clean:
	rm -rf *.o hw10_p0
